### PR TITLE
Added method for adding screenshot in report

### PR DESCRIPTION
**Pull request by elaya2410**
Added public method for attaching screenshot in extent report

### CODE REVIEW

**Comment by thomasdeurloo** [comment]
Hi, coincidentally i was looking into this today as well. Can you add other methods to add a steplog and a screenshot with a title as well? I have the methods below. Might it be better to throw the exceptions instead of printing the stacktrace? People need to write their own wrapper in a util class or something.

```
public static synchronized void addStepLog(final String message){
        stepTestThreadLocal.get().info(message);
    }

public static synchronized void addStepScreenCaptureFromPath(final String imagePath) throws IOException {
        stepTestThreadLocal.get().addScreenCaptureFromPath(imagePath);
    }

public static synchronized void addStepScreenCaptureFromPath(final String imagePath, final String title) throws IOException {
        stepTestThreadLocal.get().addScreenCaptureFromPath(imagePath, title);
    }
```

**Comment by elaya2410** [comment]
Thanks thomas for your input. I have added the methods as you suggested.

**Comment by gheeno** [comment]
When is the merge date?

**Comment by anshooarora** [comment]
All - happy to merge this, but how is the above different from using hooks:

```
@After
public void after(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}

@AfterStep
public void afterStep(Scenario scenario) {
    scenario.embed(extractBytes("img.png"), "image/png");
}
```

**Comment by far11ven** [comment]
@anshooarora : I tried to add snapshot using the following code, but it doesn't embed the screenshot:

```
    @After(order = 1)
    public void afterScenario(Scenario scenario) {
        final byte[] screenShot = ((TakesScreenshot) driver).getScreenshotAs(OutputType.BYTES);
        scenario.embed(screenShot, "image/png");
    }
```
Where as following code works:

`ExtentCucumberAdapter.addStepScreenCaptureFromPath(screensotsPath);`

**Comment by elaya2410** [comment]
@anshooarora - I tried using hooks, but embed is not working.
@far11ven - Thanks for checking.

**Comment by anshooarora** [comment]
Merged

**Comment by elaya2410** [comment]
Thank you.

**Pull request merged**
