### PR TITLE
Added support for Cucumber 4.2.6

### PR DESCRIPTION
**Pull request by jdhmoreno**
Need to use Extent reports but with latest cucumber version 4.2.6.
Found that the missing bit is a class from cucumber-core called URLOutputStream that changed from 'cucumber.runtime.io' (on 4.0.1) to 'cucumber.runtime.formatter' (on 4.2.6). Also the access level changed from public to package so it cannot just be imported.
Good thing is that the class is standalone and has no other dependencies so I've just added it to the Extent codebase.
Hope it helps.

### CODE REVIEW

**Comment by anshooarora** [comment]
Merged, thank you

**Comment by jdhmoreno** [comment]
Great! good to hear. Any idea when it will be released? 1.0.7 doesn't seem to have it.
thanks in advance!

**Comment by boehlke** [comment]
Hello, I noticed that the release 1.0.7 does not contain changes after commit "update extent version (4.0.9)" (87051b3). Could you release the latest changes please?
Thank you!

**Comment by foursyth** [comment]
I will give @anshooarora a nudge to release 1.0.8.

**Pull request merged**
